### ISSUE TITLE
Entity not available: sensor.config_result

### ISSUE THREAD

**Issue by Kouwe-sudo** [apop880/config-check#10]
Config Check worked fine and was easy to use but all of a sudden it doesn't work anymore because one of the entities seems to have gone. I believe you didn't change anything and so didn't I. It says: 'Entity not available: sensor.config_result'. Does this sound familiar and do you have any clue? Or is this new to you too?
Can I fix it by just adding a new entity? But then it's still very strange that it disappeared. I already try "Reinstall" That didn't help. The entity should be self-installing or not?

**Comment by Kouwe-sudo** [comment]
Solved for the moment. It went like it came: silently. I removed the HomeAssistant Database, restarted and there the entity was again.

**Comment by apop880** [comment]
@Kouwe-sudo The entity is created and managed by the script, not by Home Assistant. When Home Assistant restarts, the entity is not persisted and is instead re-created by AppDaemon after the restart. So, if you see an error that the entity is unavailable, it should only take place at Home Assistant startup and be temporary. If you continue to see that the entity does not exist long after startup, then please let me know. I would also need to know where you are seeing that error message (Home Assistant frontend, Home Assistant logs, AppDaemon logs, or somewhere else).

Closing this issue as it sounds like it is working for you now, but if you run into this again, please open a new issue with the information listed above.
