### ISSUE TITLE
No active development?

### ISSUE THREAD

**Issue by TargetCrafter** [apop880/config-check#11]
Is this still under development?

In the readme there is a line "Note: Folder Watcher support currently does not support split configuration files" and something about this being planned for a future release. It's been 6 months, and no new release just yet. My config is split into multiple files, so i can't use this plugin even though it look awesome!

**Comment by apop880** [comment]
Hey @TargetCrafter, thanks for reaching out. This is still on my roadmap, I just haven't had as much time to commit to Home Assistant lately. But it is still in the works.
