### ISSUE TITLE
Help needed with HACS

### ISSUE THREAD

**Issue by emouawad** [apop880/config-check#4]
Not sure what's the issue here but from the Wiki it appears there was support for HACS but now i can't seem to find this component there.

Am i looking for the wrong component name?
or this component has been outdated and lost support of HACS?

**Comment by apop880** [comment]
@emouawad Sorry for the delay. This is still available in HACS. You likely don't have HACS set up to show AppDaemon apps, as that functionality is not available by default. See here for instructions on how to configure: https://hacs.xyz/docs/categories/appdaemon_apps
