### ISSUE TITLE
sensor.config_result does not exist

### ISSUE THREAD

**Issue by foxsam21** [apop880/config-check#5]
I am getting this error when I try to add the `sensor.config_result` item. 
![check_config](https://user-images.githubusercontent.com/11862524/67442024-318dfb00-f5cd-11e9-84a4-41eb6cd076c7.png)

**Comment by foxsam21** [comment]
Closing. There was a typo in the dirname so it was not loading.

**Comment by JackPoint** [comment]
@foxsam21 I have the same error, but don't know what you mean by typo in the dirname? Where can I find that?

**Comment by seventhsite** [comment]
Same error.  Any solutions?

**Comment by foxsam21** [comment]
Honestly I don't recall the exact mistake but it was a mistake **_I_** made so I would suggest to double and triple check everything.
