### ISSUE TITLE
sensor.config_result not created

### ISSUE THREAD

**Issue by kaizersoje** [apop880/config-check#7]
Hi, I am not sure what's wrong but the sensor.config_result is not getting created. What am I doing wrong?

**Comment by apop880** [comment]
@kaizersoje Is there anything in your AppDaemon logs when the app initializes?

**Comment by kaizersoje** [comment]
I didn't get you. I am not sure how to configure appdaemon apps for logging.

**Comment by apop880** [comment]
@kaizersoje How do you have AppDaemon installed? Via the Home Assistant add-on or standalone?

**Comment by kaizersoje** [comment]
Ohhh... I haven't installed AppDaemon. Did not know I had to. Is this the [addon](https://github.com/hassio-addons/addon-appdaemon)  you are referring to?

**Comment by apop880** [comment]
Yes, that is the one. Go ahead and install that add-on and then you should be able to get this app working.

**Comment by kaizersoje** [comment]
all good, works now. Thanks.
